### ISSUE TITLE
adapter crashing after "upnp.0 firstDevLookup for undefined"

### ISSUE THREAD

**Issue by jens-maus** [Jey-Cee/ioBroker.upnp#8]
After a fresh install, the adapter seem to collect all necessary information for all of my UPNP devices, but then afterwards crashes with the following backtrace:

```
[...]
2017-02-18 21:05:46.923  - info: upnp.0 Found 20 devices
2017-02-18 21:05:46.923  - info: upnp.0 firstDevLookup for undefined
2017-02-18 21:05:46.927  - error: upnp.0 uncaught exception: undefined is not a valid uri or options object.
2017-02-18 21:05:46.929  - error: upnp.0 Error: undefined is not a valid uri or options object.
    at request (/opt/iobroker/node_modules/iobroker.upnp/node_modules/request/index.js:46:11)
    at firstDevLookup (/opt/iobroker/node_modules/iobroker.upnp/main.js:171:5)
    at null._onTimeout (/opt/iobroker/node_modules/iobroker.upnp/main.js:135:9)
    at Timer.listOnTimeout (timers.js:92:15)
2017-02-18 21:05:51.593  - ESC[31merrorESC[39m: host.bilbo instance system.adapter.upnp.0 terminated with code 0 (OK)
```

Please note that in https://github.com/Jey-Cee/ioBroker.upnp/blob/master/main.js#L135 you are calling `firstDevLookup()` with the `adapter.config.rootXMLurl` parameter, but here it is actually empty per default, thus `undefined`. What should I enter here?

**Comment by Jey-Cee** [comment]
Experimental function deleted.
